### ISSUE TITLE
EasyDriver.cpp:114: error: 'usleep' was not declared in this scope     usleep(sleepDelay);                      ^

### ISSUE THREAD

**Issue by vprithiviraj** [derekmolloy/beagleboneQT#1]
Why this error has come?
I haen't changed anything in this code. I'm new to Qt. so lcan you tell me, where should i declare this usleep

**Comment by wyworak** [comment]
There is no standard C API for milliseconds, so (on Unix) you will have to settle for usleep, which accepts microseconds:
`#include <unistd.h>`
`unsigned int microseconds;`
`...`
`usleep(microseconds);`

But, maybe the error was caused because you don´t declared the unistd library:
`#include <unistd.h>`

**Comment by vprithiviraj** [comment]
Thanks, I got it worked...
